# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  format:
    cmds:
      - gofmt .
    silent: true
  main:
    cmds:
      - go run .
    silent: true
